version: '3'

services:
  nginxproxy:
    #image: eforce21/letsencrypt-nginx-proxy
    image: jwilder/nginx-proxy
    container_name: nginxproxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - LETSENCRYPT_EMAIL=raz.friman@razfriman.com
  razapp:
    image: rfriman/raz-app:latest
    container_name: razapp
    environment:
      - VIRTUAL_HOST=www.razfriman.com,razfriman.com
  postgres:
     image: postgres:latest
     container_name: postgres
     environment:
         POSTGRES_USER: test
         POSTGRES_PASSWORD: test
         POSTGRES_DB: scavengercity
     volumes:
       - pgdata:/var/lib/postgresql/data
     ports:
       - 5432:5432
  backend:
    image: rfriman/scavenger-city-api:latest
    container_name: backend
    ports:
       - 5000:80
    depends_on:
       - "postgres"
    environment:
      - VIRTUAL_HOST=api.scavenger.city
  frontend:
    image: rfriman/scavenger-city:latest
    container_name: frontend
    environment:
      - VIRTUAL_HOST=app.scavenger.city
  wordpress_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    volumes:
      - wp-content:/var/www/html
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      VIRTUAL_HOST: "www.scavenger.city,scavenger.city"
volumes:
  pgdata:
  db_data:
  wp-content:












^G Get Help                      ^O WriteOut                      ^R Read File                     ^Y Prev Page                     ^K Cut Text                      ^C Cur Pos
^X Exit                          ^J Justify                       ^W Where Is                      ^V Next Page                     ^U UnCut Text                    ^T To Spell
