version: '3.4'

services:
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf.erb:/var/lib/nginx-conf/default.conf.erb:ro
      - ./nginx/default.ssl.conf.erb:/var/lib/nginx-conf/default.ssl.conf.erb:ro
      - certs:/var/lib/https-port
    environment:
      DOMAINS: 'scavenger.city -> http://wordpress, app.scavenger.city -> http://frontend, api.scavenger.city -> http://backend'
      STAGE: local

  backend:
    build:
      context: ./Backend
      dockerfile: ./Dockerfile
    image: registry.gitlab.com/raz.friman/scavenger-city/scavenger-city-backend:latest
    ports:
       - 5000:80
    depends_on:
       - "postgres"

  frontend:
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile
    image: registry.gitlab.com/raz.friman/scavenger-city/scavenger-city-frontend:latest

  wordpress_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress 

  postgres:
     image: postgres:latest
     container_name: postgres
     environment:
         POSTGRES_USER: test
         POSTGRES_PASSWORD: test
         POSTGRES_DB: scavengercity
     volumes:
       - pgdata:/var/lib/postgresql/data
     ports:
       - 5432:5432
  
  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    volumes:
      - wp-content:/var/www/html
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      VIRTUAL_HOST: "www.scavenger.city,scavenger.city"
volumes:
  certs:
  pgdata:
  db_data:
  wp-content:  