version: '3'

services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: watchtower nginxproxy razapp postgres backend frontend --interval 30
    restart: unless-stopped
  nginxproxy:
    #image: eforce21/letsencrypt-nginx-proxy
    image: jwilder/nginx-proxy
    container_name: nginxproxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - LETSENCRYPT_EMAIL=raz.friman@razfriman.com
  razapp:
    image: rfriman/raz-app:latest
    container_name: razapp
    environment:
      - VIRTUAL_HOST=www.razfriman.com,razfriman.com
  postgres:
     image: postgres:latest
     container_name: postgres
     environment:
         POSTGRES_USER: test
         POSTGRES_PASSWORD: test
         POSTGRES_DB: scavengercity
     volumes:
       - pgdata:/var/lib/postgresql/data
     ports:
       - 5432:5432
  backend:
    image: rfriman/scavenger-city-api:latest
    container_name: backend
    ports:
       - 5000:80
    depends_on:
       - "postgres"
    environment:
      - VIRTUAL_HOST=api.razfriman.com
  frontend:
    image: rfriman/scavenger-city:latest
    container_name: frontend
    environment:
      - VIRTUAL_HOST=scavengercity.razfriman.com
volumes:
  pgdata: