version: '3'

services:
  nginx-proxy:
    image: eforce21/letsencrypt-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - LETSENCRYPT_EMAIL=raz.friman@razfriman.com
  razapp:
    image: rfriman/raz-app
    environment:
      - VIRTUAL_HOST=www.razfriman.com,razfriman.com
  postgres:
     image: postgres
     environment:
         POSTGRES_USER: test
         POSTGRES_PASSWORD: test
         POSTGRES_DB: scavengercity
     volumes:
       - pgdata:/var/lib/postgresql/data
     ports:
       - 5432:5432
  api:
    image: rfriman/scavenger-city-api
    ports:
       - 5000:80
    depends_on:
       - "postgres"
    environment:
      - VIRTUAL_HOST=api.razfriman.com
  frontend:
    image: rfriman/scavenger-city
    environment:
      - VIRTUAL_HOST=scavengercity.razfriman.com
volumes:
  pgdata:
